### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlab-webrtc-docprovider#5]
### Checklist

> could use releaser, but meh

- [x] start a release issue with a checklist (maybe like this one)
- [x] merge all outstanding PRs
- [x] ensure the versions have been bumped
- [x] ensure the CHANGELOG is up-to-date
  - [x] move the new release to the top of the stack
- [x] validate on binder
- [x] wait for a successful build of `main`
- [x] download the `dist` archive and unpack somewhere (maybe a fresh `dist`)
- [x] create a new release through the GitHub UI
  - [x] paste in the relevant CHANGELOG entries
  - [x] upload the artifacts
- [x] actually upload to npm.com, pypi.org
- [x] postmortem
  - [x] handle `conda-forge` feedstock tasks https://github.com/conda-forge/staged-recipes/pull/18725
  - [x] validate on binder via simplest-possible gists https://gist.github.com/bollwyvl/c5a287f6702b5e1d788a4cd704d596d9
  - [x] bump to next development version
  - [x] update release procedures https://github.com/jupyterlite/jupyterlab-webrtc-docprovider/pull/11

**Comment by jtpio** [comment]
Wasn't the repository generated from the cookiecutter?

If so then it should already be compatible with the releaser, and almost all the steps mentioned in above already handled.
